# Generated by Django 3.1.7 on 2021-02-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=250, unique=True, verbose_name='SID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webrtc.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Sdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_sdp', models.TextField(verbose_name='Broadcast Offer')),
                ('to_user_sdp', models.TextField(verbose_name='Recieve Offer')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='webrtc.userprofile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='webrtc.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Ice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice', models.TextField(verbose_name='Ice')),
                ('sdp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webrtc.sdp')),
            ],
        ),
    ]
