# Generated by Django 3.1.7 on 2021-02-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webrtc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdp',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='webrtc.userprofile'),
        ),
        migrations.AlterField(
            model_name='sdp',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='webrtc.userprofile'),
        ),
    ]
