# Generated by Django 3.1.7 on 2021-02-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webrtc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdp', models.TextField(verbose_name='Sdp')),
                ('conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webrtc.userconnection')),
            ],
        ),
        migrations.CreateModel(
            name='Ice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice', models.TextField(verbose_name='Ice')),
                ('sdp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webrtc.sdp')),
            ],
        ),
    ]
