version: '3.5'
services: 
    webrtc-django:
        build: .
        ports:
            - 8000:8000
        working_dir: /app
        container_name: webrtc-django
        command: '/entry/entrypoint.sh'
        volumes:
            - .:/app
        networks: 
            - webrtc_network

    webrtc-celery-worker:
        build: .
        working_dir: /app
        command: celery -A app worker -l info
        volumes:
            - .:/app
        depends_on:
            - webrtc-redis-server
        container_name: webrtc-celery-worker
        networks: 
            - webrtc_network

    webrtc-socketio-server:
        build: .
        working_dir: /app
        command: ./manage.py start_socket
        volumes:
            - .:/app
        depends_on:
            - webrtc-redis-server
        container_name: webrtc-socketio-server
        ports:
            - 5001:5001
        networks: 
            - webrtc_network

    webrtc-redis-server:
        image: "redis:alpine"
        container_name: webrtc-redis-server
        networks: 
            - webrtc_network

    webrtc-nginx-server:
        build: 
            context: .
            dockerfile: Dockerfile.nginx
            args:
                - NGINX_PORT=80
        container_name: webrtc-nginx-server
        # restart: always
        ports:
            - 80:80
        volumes:
            - .:/app
        depends_on:
            - webrtc-django
        networks: 
            - webrtc_network


networks:
    webrtc_network:
        driver: bridge